### ISSUE TITLE
trouble loading neurosynth dataset

### ISSUE THREAD

**Issue by mriedel56** [neurostuff/NiMARE#209]
downloaded and converted the neurosynth dataset to a nimare compatible dataset as described in the exampled, but when loading in the MACM workflow, received the following error:

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nimare/workflows/macm.py", line 21, in macm_workflow
    dset = Dataset(dataset_file)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nimare/dataset.py", line 42, in __init__
    self.data = json.load(f_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by tsalo** [comment]
I'm having trouble reproducing your error. Could you give me a bit more information? What version of NiMARE are you using? If you installed it with git, you can do `git log`.

Another problem is that the MACM workflow is not currently designed to work with Neurosynth. Namely, it uses ALE, and doesn't include any arguments or defaults to fill in Neurosynth's sample sizes, so with the current version you should end up with something like the following:

```bash
PSY2723:current_data tsalo$ nimare macm --mask V1_ROI.nii.gz --n_iters 100 --n_cores 1 --prefix V1 neurosynth_nimare.json 
INFO:nimare.workflows.macm:Loading coordinates...
WARNING:nimare.dataset:Not applying transforms to coordinates in unrecognized space "UNKNOWN"
Traceback (most recent call last):
  File "/Users/tsalo/anaconda/envs/python3/bin/nimare", line 11, in <module>
    load_entry_point('NiMARE', 'console_scripts', 'nimare')()
  File "/Users/tsalo/Documents/tsalo/NiMARE/nimare/cli.py", line 405, in _main
    options.func(**args)
  File "/Users/tsalo/Documents/tsalo/NiMARE/nimare/workflows/macm.py", line 25, in macm_workflow
    n_subs_db = dset.coordinates.drop_duplicates('id')['n'].astype(float).astype(int).sum()
  File "/Users/tsalo/anaconda/envs/python3/lib/python3.6/site-packages/pandas/core/generic.py", line 5882, in astype
    dtype=dtype, copy=copy, errors=errors, **kwargs
  File "/Users/tsalo/anaconda/envs/python3/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 581, in astype
    return self.apply("astype", dtype=dtype, **kwargs)
  File "/Users/tsalo/anaconda/envs/python3/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 438, in apply
    applied = getattr(b, f)(**kwargs)
  File "/Users/tsalo/anaconda/envs/python3/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 559, in astype
    return self._astype(dtype, copy=copy, errors=errors, values=values, **kwargs)
  File "/Users/tsalo/anaconda/envs/python3/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 643, in _astype
    values = astype_nansafe(vals1d, dtype, copy=True, **kwargs)
  File "/Users/tsalo/anaconda/envs/python3/lib/python3.6/site-packages/pandas/core/dtypes/cast.py", line 700, in astype_nansafe
    "Cannot convert non-finite values (NA or inf) to " "integer"
ValueError: Cannot convert non-finite values (NA or inf) to integer
```

If that's a functionality you'd like to see, would you mind opening an issue for it? Otherwise, you can use Python code to run a MACM using either ALE, SCALE, or MKDA Chi2 instead of the CLI workflow.

**Comment by mriedel56** [comment]
I figured out I was using an old version, where the methods for loading a Dataset have changed. Closing this as it is not an issue.
