### ISSUE TITLE
Example breaking docs build

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#418]
Here's the traceback from [here](https://app.circleci.com/pipelines/github/neurostuff/NiMARE/956/workflows/065f575e-1037-49e8-9e09-2af981477db5/jobs/4181):

```
Extension error:
Here is a summary of the problems encountered when running the examples

Unexpected failing examples:
/tmp/src/NiMARE/examples/02_meta-analyses/plot_simulated_data.py failed leaving traceback:
Traceback (most recent call last):
  File "/opt/conda/envs/py36_env/lib/python3.6/site-packages/sphinx_gallery/scrapers.py", line 335, in save_figures
    rst = scraper(block, block_vars, gallery_conf)
  File "/opt/conda/envs/py36_env/lib/python3.6/site-packages/sphinx_gallery/scrapers.py", line 151, in matplotlib_scraper
    fig.savefig(image_path, **these_kwargs)
  File "/opt/conda/envs/py36_env/lib/python3.6/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/conda/envs/py36_env/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2217, in print_figure
    **kwargs)
  File "/opt/conda/envs/py36_env/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/py36_env/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    FigureCanvasAgg.draw(self)
  File "/opt/conda/envs/py36_env/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 407, in draw
    self.figure.draw(self.renderer)
  File "/opt/conda/envs/py36_env/lib/python3.6/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/opt/conda/envs/py36_env/lib/python3.6/site-packages/matplotlib/figure.py", line 1837, in draw
    pos = locator(ax, renderer)
  File "/opt/conda/envs/py36_env/lib/python3.6/site-packages/nilearn/plotting/displays.py", line 1662, in _locator
    return transforms.Bbox([[left_dict[axes], y0],
KeyError: <matplotlib.axes._axes.Axes object at 0x7f697d4bf3c8>
```

This is happening in #417, but also in the RTD build for `latest`, so it's not something introduced in #417. I'm not sure if we accidentally merged in a bug, if there's an update to one of the dependencies, or what.

**Comment by tsalo** [comment]
This bug appears intermittently and can often be resolved by just restarting the build/workflow, so I will label it as low priority.
