### ISSUE TITLE
Memory issue with kernel transformation on large datasets

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#452]
## Summary

The CorrelationDecoder works by generating MA maps for all studies in the Dataset. Those MA maps are saved to files to reduce memory usage, but the initial step is causing an out-of-memory issue with the full Neurosynth dataset.

## Additional details

- NiMARE version: 0.0.7

### What were you trying to do?
Run a CorrelationDecoder on the Neurosynth dataset.

### What did you expect to happen?
I would expect the decoder to be very slow, but it should run successfully.

### What actually happened?
```
Traceback (most recent call last):
  File "listings_figures_and_tables.py", line 620, in <module>
    decoder.fit(ns_dset)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/NiMARE/nimare/base.py", line 417, in fit
    self._fit(dataset)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/NiMARE/nimare/decode/continuous.py", line 183, in _fit
    dataset = kernel_transformer.transform(dataset, return_type="dataset")
  File "/home/data/nbc/misc-projects/Salo_NiMARE/NiMARE/nimare/meta/kernel.py", line 161, in transform
    transformed_maps = self._transform(mask, coordinates)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/NiMARE/nimare/meta/kernel.py", line 292, in _transform
    dims, vox_dims, ijks, self.r, self.value, exp_idx, sum_overlap=self._sum_overlap
  File "/home/data/nbc/misc-projects/Salo_NiMARE/NiMARE/nimare/meta/utils.py", line 303, in compute_kda_ma
    kernel_data = np.zeros([n_studies] + list(shape), dtype=type(value))
numpy.core._exceptions.MemoryError: Unable to allocate 96.6 GiB for an array with shape (14371, 91, 109, 91) and data type int64
```

## Reproducing the bug

```python
import nimare

nimare.extract.fetch_neurosynth("data/", unpack=True)
ns_dset = nimare.io.convert_neurosynth_to_dataset(
    "data/database.txt",
    "data/features.txt",
)
decoder = nimare.decode.continuous.CorrelationDecoder(
    feature_group="Neurosynth_tfidf",
    frequency_threshold=0.001,
    meta_estimator=nimare.meta.cbma.mkda.MKDAChi2,
    target_image="z_desc-specificity",
)
decoder.fit(ns_dset)
```

**Comment by tsalo** [comment]
I think there are two good options:

1. Loop over contrasts and transform each one, then combine them in `KernelTransformer.transform`. This won't fix the issue if `return_type == "image"`, but it should help a little bit if `return_type == "array"` and it should completely eliminate the space issue if `return_type == "dataset"`.
2. Use memory-mapped files arrays.

Either option could potentially use a `low_memory` option or automated Dataset size check to toggle whether the new approach is used.
