### ISSUE TITLE
Recent changes to kernel transformers raise memory usage at masking step

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#470]
## Summary

Our recent changes to the way kernel transformers operate under low-memory conditions (#453, #460, #462, #463) unfortunately have uncovered an issue with apply maskers to large imaging files (or lists of files) that seems to be driven by how `nilearn` loads the images into memory.

Before our recent changes, the MA maps were generated from scratch automatically, even when they _should_ have been loaded from the `Dataset.images` attribute instead. Somehow, using nilearn on files requires more memory at masking than using it on img objects? I'm not 100% sure.

## Additional details

- NiMARE version: ~0.0.7 (dev)

### What were you trying to do?
Run a CorrelationDecoder on the full Neurosynth database (~14k studies).

### What did you expect to happen?
I expected the CorrelationDecoder to run successfully, with MA maps (saved as files) loaded into memory without issue.

### What actually happened?
Here's the traceback from a CorrelationDecoder with MDKAChi2, run on only 5k studies from Neurosynth:

```bash
INFO:nimare.meta.cbma.mkda:Loading pre-generated MA maps for Dataset 1.
INFO:nimare.meta.cbma.mkda:Loading pre-generated MA maps for Dataset 2.
Traceback (most recent call last):
  File "listings_figures_and_tables_part3.py", line 56, in <module>
    decoder.fit(ns_dset_first5000)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/NiMARE/nimare/base.py", line 417, in fit
    self._fit(dataset)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/NiMARE/nimare/decode/continuous.py", line 188, in _fit
    self.meta_estimator.fit(feature_dset, nonfeature_dset)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/NiMARE/nimare/meta/cbma/base.py", line 671, in fit
    maps = self._fit(dataset1, dataset2)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/NiMARE/nimare/meta/cbma/mkda.py", line 219, in _fit
    ma_maps2 = self.masker.transform(self.inputs_["ma_maps2"])
  File "/home/data/nbc/misc-projects/Salo_NiMARE/nimare-paper/conda_env/lib/python3.7/site-packages/nilearn/input_data/base_masker.py", line 176, in transform
    return self.transform_single_imgs(imgs, confounds)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/nimare-paper/conda_env/lib/python3.7/site-packages/nilearn/input_data/nifti_masker.py", line 408, in transform_single_imgs
    dtype=self.dtype
  File "/home/data/nbc/misc-projects/Salo_NiMARE/nimare-paper/conda_env/lib/python3.7/site-packages/joblib/memory.py", line 352, in __call__
    return self.func(*args, **kwargs)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/nimare-paper/conda_env/lib/python3.7/site-packages/nilearn/input_data/nifti_masker.py", line 58, in filter_and_mask
    dtype=dtype)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/nimare-paper/conda_env/lib/python3.7/site-packages/nilearn/input_data/base_masker.py", line 99, in filter_and_extract
    memory_level=memory_level)(imgs)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/nimare-paper/conda_env/lib/python3.7/site-packages/joblib/memory.py", line 352, in __call__
    return self.func(*args, **kwargs)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/nimare-paper/conda_env/lib/python3.7/site-packages/nilearn/input_data/nifti_masker.py", line 31, in __call__
    dtype=img_data_dtype(imgs)), imgs.affine)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/nimare-paper/conda_env/lib/python3.7/site-packages/nilearn/masking.py", line 761, in apply_mask
    ensure_finite=ensure_finite)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/nimare-paper/conda_env/lib/python3.7/site-packages/nilearn/masking.py", line 804, in _apply_mask_fmri
    copy=True)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/nimare-paper/conda_env/lib/python3.7/site-packages/nilearn/_utils/numpy_conversions.py", line 110, in as_ndarray
    ret = _asarray(arr, dtype=dtype, order=order)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/nimare-paper/conda_env/lib/python3.7/site-packages/nilearn/_utils/numpy_conversions.py", line 27, in _asarray
    ret = np.asarray(arr, dtype=dtype, order=order)
  File "/home/data/nbc/misc-projects/Salo_NiMARE/nimare-paper/conda_env/lib/python3.7/site-packages/numpy/core/_asarray.py", line 102, in asarray
    return array(a, dtype, copy=False, order=order)
numpy.core._exceptions.MemoryError: Unable to allocate 33.3 GiB for an array with shape (91, 109, 91, 4956) and data type int64
```

## Reproducing the bug

This bug can be reproduced with the code at https://github.com/NBCLab/nimare-paper/blob/23c265098337d4d09e37c15bf42fdd12a2d6894d/listings_figures_and_tables_part3.py#L13-L58. To reproduce from scratch you'll need to download the Neurosynth dataset.

**Comment by tsalo** [comment]
It seems like this is something that should be addressed within `nilearn`. Perhaps by leveraging `indexed_gzip`? We need to dig into it before we can come up with a game plan.

**Comment by tsalo** [comment]
In the meantime, maybe we can implement a loop. Basically, we do a quick calculation of expected memory based on (1) loading the first file into memory and checking the size and (2) the number of files in the Dataset, and then, if that number's very big, we just preallocate an array (even memmapped!) and loop through the files, unmasking each and adding it to the array one by one.
