### ISSUE TITLE
`_check_same_fov` failing on pain Dataset IBMA with nilearn 0.8.1dev0

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#543]
## Summary

The weird thing is that [`_check_same_fov`](https://github.com/nilearn/nilearn/blob/e6591d8907ceae55eea6f04ce181acb6a12743b5/nilearn/_utils/niimg_conversions.py#L33-L68) hasn't been touched since January. Additionally, it doesn't seem to contain any calls to anything else that might have changed. It's actually very simply comparing affines with `np.allclose`.

Switching from 0.8.0 to 0.8.1dev0 (using `python setup.py develop` on my fork) doesn't seem to change any dependencies, so... I honestly have no clue where this is coming from.

## Additional details

- NiMARE version: ~0.0.10rc1 (https://github.com/neurostuff/NiMARE/commit/80642d1e2752943e5d4b3c325e1cfc356e50a8b6)
- nilearn version: 0.8.1dev0 (https://github.com/nilearn/nilearn/commit/0b29395feae8d0c75da56ebe3095bfa315214542)
- numpy version: 1.21.0 (see #542 for why it's not 1.21.1)

### What were you trying to do?

Run the `plot_ibma` example.

### What did you expect to happen?

For it to run, or for it to consistently raise an error about the FOVs.

### What actually happened?

With 0.8.0, it runs fine. With 0.8.1, I get this:

```
/Users/taylor/Documents/tsalo/nilearn/nilearn/datasets/struct.py:326: FutureWarning: Default resolution of the MNI template will change from 2mm to 1mm in version 0.10.0
  warnings.warn("Default resolution of the MNI template will change "
INFO:nimare.utils:Shared path detected: '/Users/taylor/.nimare/nidm_21pain/'
/Users/taylor/Documents/tsalo/nilearn/nilearn/image/resampling.py:594: RuntimeWarning: NaNs or infinite values are present in the data passed to resample. This is a bad thing as they make resampling ill-defined and much slower.
  _resample_one_img(data[all_img + ind], A, b, target_shape,
/Users/taylor/Documents/tsalo/nilearn/nilearn/image/resampling.py:594: RuntimeWarning: NaNs or infinite values are present in the data passed to resample. This is a bad thing as they make resampling ill-defined and much slower.
  _resample_one_img(data[all_img + ind], A, b, target_shape,
/Users/taylor/Documents/tsalo/nilearn/nilearn/image/resampling.py:594: RuntimeWarning: NaNs or infinite values are present in the data passed to resample. This is a bad thing as they make resampling ill-defined and much slower.
  _resample_one_img(data[all_img + ind], A, b, target_shape,
/Users/taylor/Documents/tsalo/nilearn/nilearn/image/resampling.py:594: RuntimeWarning: NaNs or infinite values are present in the data passed to resample. This is a bad thing as they make resampling ill-defined and much slower.
  _resample_one_img(data[all_img + ind], A, b, target_shape,
/Users/taylor/Documents/tsalo/nilearn/nilearn/image/resampling.py:594: RuntimeWarning: NaNs or infinite values are present in the data passed to resample. This is a bad thing as they make resampling ill-defined and much slower.
  _resample_one_img(data[all_img + ind], A, b, target_shape,
/Users/taylor/Documents/tsalo/nilearn/nilearn/image/resampling.py:594: RuntimeWarning: NaNs or infinite values are present in the data passed to resample. This is a bad thing as they make resampling ill-defined and much slower.
  _resample_one_img(data[all_img + ind], A, b, target_shape,
/Users/taylor/Documents/tsalo/nilearn/nilearn/image/resampling.py:594: RuntimeWarning: NaNs or infinite values are present in the data passed to resample. This is a bad thing as they make resampling ill-defined and much slower.
  _resample_one_img(data[all_img + ind], A, b, target_shape,
/Users/taylor/Documents/tsalo/nilearn/nilearn/image/resampling.py:594: RuntimeWarning: NaNs or infinite values are present in the data passed to resample. This is a bad thing as they make resampling ill-defined and much slower.
  _resample_one_img(data[all_img + ind], A, b, target_shape,
/Users/taylor/Documents/tsalo/nilearn/nilearn/image/resampling.py:594: RuntimeWarning: NaNs or infinite values are present in the data passed to resample. This is a bad thing as they make resampling ill-defined and much slower.
  _resample_one_img(data[all_img + ind], A, b, target_shape,
/Users/taylor/Documents/tsalo/nilearn/nilearn/image/resampling.py:594: RuntimeWarning: NaNs or infinite values are present in the data passed to resample. This is a bad thing as they make resampling ill-defined and much slower.
  _resample_one_img(data[all_img + ind], A, b, target_shape,
INFO:nimare.utils:Shared path detected: '/Users/taylor/.nimare/nidm_21pain/'
Traceback (most recent call last):
  File "plot_ibma.py", line 36, in <module>
    meta.fit(dset)
  File "/Users/taylor/Documents/tsalo/NiMARE/nimare/base.py", line 296, in fit
    self._preprocess_input(dataset)
  File "/Users/taylor/Documents/tsalo/NiMARE/nimare/base.py", line 356, in _preprocess_input
    _check_same_fov(**check_imgs, reference_masker=mask_img, raise_error=True)
  File "/Users/taylor/Documents/tsalo/nilearn/nilearn/_utils/niimg_conversions.py", line 65, in _check_same_fov
    raise ValueError('Following field of view errors were detected:\n' +
ValueError: Following field of view errors were detected:
- /Users/taylor/.nimare/nidm_21pain/pain_01.nidm/Contrast.nii.gz and reference_masker do not have the same shape
- /Users/taylor/.nimare/nidm_21pain/pain_01.nidm/Contrast.nii.gz and reference_masker do not have the same affine
- /Users/taylor/.nimare/nidm_21pain/pain_02.nidm/Contrast.nii.gz and reference_masker do not have the same shape
- /Users/taylor/.nimare/nidm_21pain/pain_02.nidm/Contrast.nii.gz and reference_masker do not have the same affine
- /Users/taylor/.nimare/nidm_21pain/pain_03.nidm/Contrast.nii.gz and reference_masker do not have the same shape
- /Users/taylor/.nimare/nidm_21pain/pain_03.nidm/Contrast.nii.gz and reference_masker do not have the same affine
- /Users/taylor/.nimare/nidm_21pain/pain_04.nidm/Contrast.nii.gz and reference_masker do not have the same shape
- /Users/taylor/.nimare/nidm_21pain/pain_04.nidm/Contrast.nii.gz and reference_masker do not have the same affine
- /Users/taylor/.nimare/nidm_21pain/pain_05.nidm/Contrast.nii.gz and reference_masker do not have the same shape
- /Users/taylor/.nimare/nidm_21pain/pain_05.nidm/Contrast.nii.gz and reference_masker do not have the same affine
- /Users/taylor/.nimare/nidm_21pain/pain_06.nidm/Contrast.nii.gz and reference_masker do not have the same shape
- /Users/taylor/.nimare/nidm_21pain/pain_06.nidm/Contrast.nii.gz and reference_masker do not have the same affine
- /Users/taylor/.nimare/nidm_21pain/pain_07.nidm/Contrast.nii.gz and reference_masker do not have the same shape
- /Users/taylor/.nimare/nidm_21pain/pain_07.nidm/Contrast.nii.gz and reference_masker do not have the same affine
- /Users/taylor/.nimare/nidm_21pain/pain_08.nidm/Contrast.nii.gz and reference_masker do not have the same shape
- /Users/taylor/.nimare/nidm_21pain/pain_08.nidm/Contrast.nii.gz and reference_masker do not have the same affine
- /Users/taylor/.nimare/nidm_21pain/pain_09.nidm/Contrast.nii.gz and reference_masker do not have the same shape
- /Users/taylor/.nimare/nidm_21pain/pain_09.nidm/Contrast.nii.gz and reference_masker do not have the same affine
- /Users/taylor/.nimare/nidm_21pain/pain_10.nidm/Contrast.nii.gz and reference_masker do not have the same shape
- /Users/taylor/.nimare/nidm_21pain/pain_10.nidm/Contrast.nii.gz and reference_masker do not have the same affine
- /Users/taylor/.nimare/nidm_21pain/pain_11.nidm/Contrast_T001.nii.gz and reference_masker do not have the same shape
- /Users/taylor/.nimare/nidm_21pain/pain_11.nidm/Contrast_T001.nii.gz and reference_masker do not have the same affine
- /Users/taylor/.nimare/nidm_21pain/pain_12.nidm/Contrast_T001.nii.gz and reference_masker do not have the same shape
- /Users/taylor/.nimare/nidm_21pain/pain_12.nidm/Contrast_T001.nii.gz and reference_masker do not have the same affine
- /Users/taylor/.nimare/nidm_21pain/pain_13.nidm/Contrast_T001.nii.gz and reference_masker do not have the same shape
- /Users/taylor/.nimare/nidm_21pain/pain_13.nidm/Contrast_T001.nii.gz and reference_masker do not have the same affine
- /Users/taylor/.nimare/nidm_21pain/pain_14.nidm/Contrast_T001.nii.gz and reference_masker do not have the same shape
- /Users/taylor/.nimare/nidm_21pain/pain_14.nidm/Contrast_T001.nii.gz and reference_masker do not have the same affine
- /Users/taylor/.nimare/nidm_21pain/pain_15.nidm/Contrast_T001.nii.gz and reference_masker do not have the same shape
- /Users/taylor/.nimare/nidm_21pain/pain_15.nidm/Contrast_T001.nii.gz and reference_masker do not have the same affine
- /Users/taylor/.nimare/nidm_21pain/pain_16.nidm/Contrast_T001.nii.gz and reference_masker do not have the same shape
- /Users/taylor/.nimare/nidm_21pain/pain_16.nidm/Contrast_T001.nii.gz and reference_masker do not have the same affine
- /Users/taylor/.nimare/nidm_21pain/pain_17.nidm/Contrast_T001.nii.gz and reference_masker do not have the same shape
- /Users/taylor/.nimare/nidm_21pain/pain_17.nidm/Contrast_T001.nii.gz and reference_masker do not have the same affine
- /Users/taylor/.nimare/nidm_21pain/pain_18.nidm/Contrast_T001.nii.gz and reference_masker do not have the same shape
- /Users/taylor/.nimare/nidm_21pain/pain_18.nidm/Contrast_T001.nii.gz and reference_masker do not have the same affine
- /Users/taylor/.nimare/nidm_21pain/pain_19.nidm/Contrast_T001.nii.gz and reference_masker do not have the same shape
- /Users/taylor/.nimare/nidm_21pain/pain_19.nidm/Contrast_T001.nii.gz and reference_masker do not have the same affine
- /Users/taylor/.nimare/nidm_21pain/pain_20.nidm/Contrast_T001.nii.gz and reference_masker do not have the same shape
- /Users/taylor/.nimare/nidm_21pain/pain_20.nidm/Contrast_T001.nii.gz and reference_masker do not have the same affine
- /Users/taylor/.nimare/nidm_21pain/pain_21.nidm/Contrast_T001.nii.gz and reference_masker do not have the same shape
- /Users/taylor/.nimare/nidm_21pain/pain_21.nidm/Contrast_T001.nii.gz and reference_masker do not have the same affine
```

## Reproducing the bug

```bash
pip install nilearn==0.8.0
python plot_ibma.py
# yay :)
pip uninstall nilearn
cd /path/to/nilearn/repo/
python setup.py develop
python plot_ibma.py
# boo :(
```

A reduced version of `plot_ibma.py`:

```python
import os

import nimare
from nimare.meta import ibma
from nimare.tests.utils import get_test_data_path

dset_dir = nimare.extract.download_nidm_pain()
dset_file = os.path.join(get_test_data_path(), "nidm_pain_dset.json")
dset = nimare.dataset.Dataset(dset_file)
dset.update_path(dset_dir)

# Calculate missing images
xformer = nimare.transforms.ImageTransformer(target=["varcope", "z"], overwrite=True)
dset = xformer.transform(dset)

# Run meta-analysis
meta = ibma.DerSimonianLaird()
meta.fit(dset)
```

**Comment by tsalo** [comment]
It looks like this could be due to the fact that `nilearn.datasets.load_mni152_brain_mask()` returns a different mask post-https://github.com/nilearn/nilearn/pull/2738.

**Comment by tsalo** [comment]
Unfortunately, it doesn't look like there are any (91, 109, 91) MNI masks still in `nilearn`, so the alternative seems to be to use `resample=True` on all IBMA Estimators in our examples. At least any that use the NIDM 21-pain dataset.
