### ISSUE TITLE
convert_neurovault_to_dataset() - sample_size and IndexError 

### ISSUE THREAD

**Issue by gnodix** [neurostuff/NiMARE#576]
Hi everyone, 

I'm trying to run a meta analysis strip to extract statistical map from NeuroVault. 

The script is : 
```python
from nimare.io import convert_neurovault_to_dataset

# The specific collections I would like to download group level
# statistical maps from

collection_ids = (2525, 9616, 3935, 3954, 3952, 6150)

# A mapping between what I want the contrast(s) to be
# named in the dataset and what their respective group
# statistical maps are named on neurovault
contrasts = {
    "dyad synchrony": (
    	"Lee 2017"
    	"van Baar 2021"
    	"Raykov 2018"
    	"Lee 2018"
    	"Lee 2017"
    	"Kerr 2020"
    )
}

# Convert how the statistical maps on neurovault are represented
# in a NiMARE dataset.
map_type_conversion = {"Z map": "z", "T map": "t"}

dset = convert_neurovault_to_dataset(
    collection_ids,
    contrasts,
    img_dir=None,
    map_type_conversion=None,
)

from nimare.transforms import ImageTransformer

# Not all studies have Z maps!
#print(dset.images["z"])

z_transformer = ImageTransformer(target="z")
dset = z_transformer.transform(dset)

# All studies now have Z maps!
#print(dset.images["z"])

from nilearn.plotting import plot_stat_map

from nimare.meta.ibma import Fishers

meta = Fishers()

meta_res = meta.fit(dset)

plot_stat_map(meta_res.get_map("z"), threshold=3.3)
# The result may look questionable, but this code provides
# a template on how to use neurovault in your meta analysis.
```

However, the terminal give me this response: 
```
Traceback (most recent call last):

  File "/Users/ginodiez/Desktop/Cogmaster/M1/LNC2/meta/statmap_neurovault.py", line 29, in <module>
    dset = convert_neurovault_to_dataset(

  File "/Users/ginodiez/opt/anaconda3/lib/python3.8/site-packages/nimare/io.py", line 544, in convert_neurovault_to_dataset
    sample_size = sample_sizes[0]

IndexError: list index out of range
```
I don't understand the "sample_size" error and how to solve it (there is no solution on the web for know!)

Best, 
Gino 

- NiMARE version: 0.0.9
- Mac OS Big Sur 11.2.3

**Comment by gnodix** [comment]
Hi @jdkent 

Think you for your help! 
Indeed, it's was the absence of the "|" sign which provide this bug.

I obtain a figure, but the format doesn't fit with the template so I will open a new request. 

Best,
