### ISSUE TITLE
Bus errors in large meta-analyses with memory_limit and pre-generated MA maps

### ISSUE THREAD

**Issue by tsalo** [neurostuff/NiMARE#631]
## Summary

When running a large meta-analysis on a Dataset with pre-generated MA maps stored in its `images` attribute, and a `memory_limit` set for the Estimator, _sometimes_ there is a bus error on the FIU HPC.

It looks like the bus error occurs as part of `_safe_transform`, when using a memmap.

## Additional details

- NiMARE version: 0.0.11

I originally noticed this problem when I started working on the NiMARE Jupyter book, which eventually led to me writing temporary files to the NiMARE data directory instead of tmpdir in #460. However, that inevitably slowed down operations on those temporary files, so I switched back in #599. My hope was that the problem would be resolved, since I never figured out the cause of the issue in the first place. 

### What were you trying to do?

Run a large MKDADensity meta-analysis using studies from Neurosynth on the FIU HPC.

### What did you expect to happen?

I expected the Estimator to successfully fit.

### What actually happened?

There was a bus error during a call to `_safe_transform`.

## Reproducing the bug

I haven't managed to successfully reproduce the bug at this point. I am running meta-analyses on subsets of the Neurosynth database for #630, with random studies. I will try to log the studies that failed, in case a certain subset of studies reliably produces the error, but in the meantime I don't have reproducible code.

UPDATE: Running the same meta-analysis on the same studies does **not** consistently raise the error.

**Comment by tsalo** [comment]
As proposed by @JulioAPeraza, setting a different `TMPDIR` environment variable fixes the problem, so it's specifically an issue with `/tmp`. I don't know if it's just an idiosyncrasy of the FIU HPC or if this will occur with other servers using the same OS, but I think I'm going to close this issue regardless.

**Comment by tsalo** [comment]
After ~21 hours, my profiling jobs failed with the following error:

```
Traceback (most recent call last):
  File "profile_kerneltransformers.py", line 151, in <module>
    mem = memory_usage((meta.fit, (red_dset_ma,)))
  File "/home/tsalo006/nimare/joblib/conda_env/lib/python3.8/site-packages/memory_profiler.py", line 377, in memory_usage
    returned = f(*args, **kw)
  File "/home/tsalo006/nimare/joblib/conda_env/lib/python3.8/site-packages/nimare/base.py", line 314, in fit
    maps = self._fit(dataset)
  File "/home/tsalo006/nimare/joblib/conda_env/lib/python3.8/site-packages/nimare/utils.py", line 695, in memmap_context
    return function(self, *args, **kwargs)
  File "/home/tsalo006/nimare/joblib/conda_env/lib/python3.8/site-packages/nimare/meta/cbma/base.py", line 78, in _fit
    ma_values = self._collect_ma_maps(
  File "/home/tsalo006/nimare/joblib/conda_env/lib/python3.8/site-packages/nimare/meta/cbma/base.py", line 165, in _collect_ma_maps
    ma_maps = _safe_transform(
  File "/home/tsalo006/nimare/joblib/conda_env/lib/python3.8/site-packages/nimare/utils.py", line 784, in _safe_transform
    masked_data = np.memmap(
  File "/home/tsalo006/nimare/joblib/conda_env/lib/python3.8/site-packages/numpy/core/memmap.py", line 267, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
OSError: [Errno 24] Too many open files
```

I _think_ that the issue is that NiMARE's memmaps are never closed, even though the associated files are deleted. I don't know if this is what was causing the bus error, but it seems like it could be related.

**Comment by tsalo** [comment]
I also get the bus error when using `/tmp`, but it happens after 7 hours instead of 4.5. I'm _guessing_ that the problem does come down to unclosed memmap files, and that #597 helped with that issue, but it didn't completely fix it. I'm stumped on how to identify the rest of the open files.
