### ISSUE TITLE
NoneType error for no group_categories

### ISSUE THREAD

**Issue by yifan0330** [neurostuff/NiMARE#825]
## Summary

When using `nimare.meta.cbmr.CBMREstimator` with `group_categories=None`, `TypeError: 'NoneType' object is not iterable` happens at a later stage if calling`CBMRInference().fit(results)`
## Additional details
```python
Traceback (most recent call last):
  File "/gpfs3/well/nichols/users/pra123/profiling/profile_cbmr.py", line 104, in <module>
    inference.fit(result=results)
  File "/well/nichols/users/pra123/anaconda3/lib/python3.11/site-packages/nimare/meta/cbmr.py", line 480, in fit
    self.create_regular_expressions()
  File "/well/nichols/users/pra123/anaconda3/lib/python3.11/site-packages/nimare/meta/cbmr.py", line 516, in create_regular_expressions
    first_group, second_group = [
                                ^
  File "/well/nichols/users/pra123/anaconda3/lib/python3.11/site-packages/nimare/meta/cbmr.py", line 517, in <listcomp>
    f"(?P<{order}>{'|'.join([re.escape(g) for g in groups])})"

TypeError: 'NoneType' object is not iterable
``` 
- NiMARE version: 0.1.1

**Comment by yifan0330** [comment]
It's fixed after this change [#821](https://github.com/neurostuff/NiMARE/pull/821)
